"""从设置行提取公开备份白名单；动态默认值在 overrides 中明确声明。"""
import json
import re
from pathlib import Path

root = Path(__file__).resolve().parents[1]
source = (root / 'music_player_desktop/pages/SettingsPage.qml').read_text(encoding='utf-8')
keys = dict(re.findall(r'^\s+(\w+): "([\w.]+)",?$', source, re.M))
categories = ['general', 'library', 'playback', 'appearance', 'download', 'source', 'accounts', 'shortcuts', 'backup', 'other', 'about']
overrides = {'ui.fontFamily': 'SystemDefault', 'appearance.dynamicArtworkEnabled': True,
             'lyrics.showTranslation': True, 'lyrics.showRomanization': False, 'tray.enabled': True}
rules = {}
category = 'general'
for line in source.splitlines():
    match = re.search(r'categoryIndex: (\d+)', line)
    if match:
        category = categories[int(match[1])]
    match = re.search(r'key: (?:page.settingKeys.(\w+)|"([\w.]+)"), type: "(\w+)"', line)
    if not match or match[3] in ['action', 'info']:
        continue
    key = keys[match[1]] if match[1] else match[2]
    option = re.search(r'optionValue: "(\w+)"', line)
    if option:
        key += '.' + option[1]
    rule = {'category': category}
    kind = match[3]
    if key in overrides:
        default = overrides[key]
    elif kind in ['toggle', 'check']:
        default = re.search(r'checked: (true|false)', line)[1] == 'true'
    elif kind == 'select':
        values = [json.loads(v) for v in re.findall(r'value:\s*("[^"]*"|\d+)', line)]
        index = re.search(r'currentIndex: (\d+)', line)
        default = values[int(index[1]) if index else 0]
        rule['values'] = values
    elif kind == 'slider':
        default = float(re.search(r'numericValue: ([\d.]+)', line)[1])
        rule['min'] = float(re.search(r'minimumValue: ([\d.]+)', line)[1])
        rule['max'] = float(re.search(r'maximumValue: ([\d.]+)', line)[1])
    elif kind == 'shortcut':
        default = re.search(r'actionLabel: "([^"]*)"', line)[1]
    else:
        raise ValueError(line)
    rule['default'] = default
    rules[key] = rule

extra = {
    'immersive.background': ('appearance', 'aura', ['aura', 'blur', 'mv']),
    'immersive.lyricStyle': ('appearance', 'fume', ['fume', 'classic', 'cadenza', 'partita', 'cappella', 'tilt', 'claddagh', 'diorama', 'monet', 'pendolo', 'sonnet', 'tempera', 'still']),
    'immersive.visualization': ('appearance', 'none', ['none', 'spectrum', 'ambient']),
    'immersive.visualHeight': ('appearance', 112, None),
    'immersive.hideDelay': ('appearance', 3, None),
    'ui.refreshRateLimit': ('general', 60, [60, 90, 120]),
    'ui.motionEnabled': ('general', True, None),
    'ui.motionStyle': ('general', 'Elegant', ['Elegant', 'Bright']),
    'source.updateNotificationsEnabled': ('source', True, None),
    'background.color': ('appearance', '#c8bad9', None),
    'background.image': ('appearance', '', None),
    'background.video': ('appearance', '', None),
    'background.wallpaper': ('appearance', '', None),
    'background.wallpaperFolder': ('appearance', '', None),
    'background.blur': ('appearance', 56, None),
    'background.autoBlurPx': ('appearance', 32, None),
    'download.folder': ('download', '', None),
}
for key, (category, default, values) in extra.items():
    rules[key] = {'category': category, 'default': default}
    if values:
        rules[key]['values'] = values
    if key in ['background.blur', 'background.autoBlurPx']:
        rules[key].update(min=0, max=192)
    if key in ['background.image', 'background.video', 'background.wallpaper', 'background.wallpaperFolder', 'download.folder']:
        rules[key]['path'] = True
# Source identity is local to the installed scripts and is deliberately excluded.
encoded = json.dumps(rules, ensure_ascii=False, indent=2, sort_keys=True)
(root / 'src/qmlbridge/settings_schema.h').write_text(
    '#pragma once\n// Generated by tools/generate_settings_schema.py.\n'
    'inline constexpr char settingsSchema[] = R"json(' + encoded + ')json";\n', encoding='utf-8')
print(f'{len(rules)} public settings')
